reorder_imports = true
wrap_comments = false
normalize_comments = false
use_try_shorthand = true
match_block_trailing_comma = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
imports_granularity="Crate"
